### ISSUE TITLE
0.11.0: Error when closing watch mode

### ISSUE THREAD

**Issue by stnwk** [shellscape/webpack-plugin-serve#144]
- Webpack Version: 4.35.3
- Operating System (or Browser): macOS latest
- Node Version: 10.15.2
- webpack-plugin-serve Version: 0.11.0

Hi :)

I just upgraded from `0.10.0` to `0.11.0` and at first everything seemed to work fine, but when I used `CTRL+C` to terminate my `yarn dev` watch mode I got the following error message:

```
TypeError: Converting circular structure to JSON                                                                   
    at JSON.stringify (<anonymous>)
    at prep (project/node_modules/webpack-plugin-serve/lib/routes.js:14:29)
    at WebpackPluginServe.on (project/node_modules/webpack-plugin-serve/lib/routes.js:102:58)
    at WebpackPluginServe.emit (events.js:194:15)
    at WebpackPluginServe.emit (project/node_modules/webpack-plugin-serve/lib/index.js:146:13)
    at watchClose.tap (project/node_modules/webpack-plugin-serve/lib/index.js:176:36)
    at SyncHook.eval (eval at create (project/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (project/node_modules/tapable/lib/Hook.js:154:20)
    at finalCallback (project/node_modules/webpack/lib/Watching.js:187:35)
    at Watching.close (project/node_modules/webpack/lib/Watching.js:206:4)
```

I think this might be related to this change https://github.com/shellscape/webpack-plugin-serve/pull/138/files#diff-52503f2920dcbf5082edfc5670ede0f1R102 in this PR https://github.com/shellscape/webpack-plugin-serve/pull/138 but I have no clue what it's about or how to fix it.

When I downgraded back to `0.10.0` everything worked again :)

What do you think? Can you help?

**Comment by shellscape** [comment]
Thanks for reporting this. Can you throw a `console.log` (or other debug statement) in the handler, before the call to `send(prep(...` to inspect what the event and data looks like?

**Comment by stnwk** [comment]
Ok, funny enough I can't reproduce it anymore, no matter what I try.

I'll close this issue for now, should I encounter the bug again i'll try to find out what `data/event` looks like and reopen it. Thanks!

**Comment by stnwk** [comment]
Ok, I managed to re-produce it, but i'm not sure how 🤷🏻‍♂️

This is what it logged into my terminal:
![image](https://user-images.githubusercontent.com/2981250/60971235-f91b2780-a323-11e9-8d8a-dc8646a55f2d.png)

The redacted lines are file paths, before the 3 files paths at the top there were much more file paths - i think every file in my entire codebase basically. I could not scroll further up :/

Does this help you?

**Comment by shellscape** [comment]
Thanks. What's the event name during the error? That'll give me a clue as to what is trying to emit an event through it. I appreciate the screenshot, but if there's any chance you could copy/paste the actual text here, that would be much more helpful.

**Comment by stnwk** [comment]
Got it! Thanks for your guidance :)

```
{ eventName: 'close',
  data:
   Compiler {
     _pluginCompat:
      SyncBailHook {
        _args: [Array],
        taps: [Array],
        interceptors: [],
        call: [Function: lazyCompileHook],
        promise: [Function: lazyCompileHook],
        callAsync: [Function: lazyCompileHook],
        _x: undefined },
     hooks:
      { shouldEmit: [SyncBailHook],
        done: [AsyncSeriesHook],
        additionalPass: [AsyncSeriesHook],
        beforeRun: [AsyncSeriesHook],
        run: [AsyncSeriesHook],
        emit: [AsyncSeriesHook],
        afterEmit: [AsyncSeriesHook],
        thisCompilation: [SyncHook],
        compilation: [SyncHook],
        normalModuleFactory: [SyncHook],
        contextModuleFactory: [SyncHook],
        beforeCompile: [AsyncSeriesHook],
        compile: [SyncHook],
        make: [AsyncParallelHook],
        afterCompile: [AsyncSeriesHook],
        watchRun: [AsyncSeriesHook],
        failed: [SyncHook],
        invalid: [SyncHook],
        watchClose: [SyncHook],
        environment: [SyncHook],
        afterEnvironment: [SyncHook],
        afterPlugins: [SyncHook],
        afterResolvers: [SyncHook],
        entryOption: [SyncBailHook] },
     name: '0',
     parentCompilation: undefined,
     outputPath:
      'PROJECT_PATH.dev-build',
     outputFileSystem:
      NodeOutputFileSystem {
        mkdirp: [Function],
        mkdir: [Function: bound mkdir],
        rmdir: [Function: bound rmdir],
        unlink: [Function: bound unlink],
        writeFile: [Function: bound writeFile],
        join: [Function: bound join] },
     inputFileSystem:
      CachedInputFileSystem {
        fileSystem: NodeJsInputFileSystem {},
        _statStorage: [Storage],
        _readdirStorage: [Storage],
        _readFileStorage: [Storage],
        _readJsonStorage: [Storage],
        _readlinkStorage: [Storage],
        _stat: [Function: bound bound ],
        _statSync: [Function: bound bound ],
        _readdir: [Function: bound readdir],
        _readdirSync: [Function: bound readdirSync],
        _readFile: [Function: bound bound readFile],
        _readFileSync: [Function: bound bound readFileSync],
        _readJson: [Function],
        _readJsonSync: [Function],
        _readlink: [Function: bound bound readlink],
        _readlinkSync: [Function: bound bound readlinkSync] },
     recordsInputPath: undefined,
     recordsOutputPath: undefined,
     records:
      { modules: [Object],
        chunks: [Object],
        prepreHash: 'x',
        preHash: 'adaebe43bb857bc12f8d',
        hash: '09c95286e9ff1f178d90',
        moduleHashs: [Object],
        chunkHashs: [Object],
        chunkModuleIds: [Object] },
     removedFiles: Set {},
     fileTimestamps: Map {},
     contextTimestamps: Map {},
     resolverFactory:
      ResolverFactory {
        _pluginCompat: [SyncBailHook],
        hooks: [Object],
        cache1: [WeakMap],
        cache2: [Map] },
     resolvers: { normal: [Object], loader: [Object], context: [Object] },
     options:
      { mode: 'development',
        context:
         'PROJECT_PATH',
        bail: false,
        target: 'web',
        performance: [Object],
        entry: [Object],
        output: [Object],
        devtool: 'cheap-module-eval-source-map',
        resolve: [Object],
        module: [Object],
        plugins: [Array],
        cache: true,
        node: [Object],
        optimization: [Object],
        resolveLoader: [Object],
        name: '0' },
     context:
      'PROJECT_PATH',
     requestShortener:
      RequestShortener {
        currentDirectoryRegExp: SomeRegExp,
        parentDirectoryRegExp: SomeRegExp,
        buildinsAsModule: false,
        buildinsRegExp: SomeRegExp,
        cache: [Map] },
     running: true,
     watchMode: true,
     _assetEmittingSourceCache: WeakMap { [items unknown] },
     _assetEmittingWrittenFiles: Map {},
     watchFileSystem:
      NodeWatchFileSystem {
        inputFileSystem: [CachedInputFileSystem],
        watcherOptions: [Object],
        watcher: null },
     wpsId: '9f88fb7',
     dependencies: undefined,
     _lastCompilationFileDependencies:
      SortableSet [Set] {
        '... a lot of file paths ...'
        _lastActiveSortFn: undefined,
        _sortFn: undefined,
        _cache: undefined,
        _cacheOrderIndependent: undefined },
     _lastCompilationContextDependencies:
      SortableSet [Set] {
        'PROJECT_PATH',
        _sortFn: undefined,
        _lastActiveSortFn: null,
        _cache: undefined,
        _cacheOrderIndependent: undefined } } }
```

**Comment by PlayMa256** [comment]
Interesting that there was no changes to the `Compiler` class since april 1st

**Comment by shellscape** [comment]
No worries!

Looks like the likely cause is `watchClose.tap(key, () => this.emit('close', compiler));` in index.js. That would line up with the data we're seeing. We'll have to omit that event, and probably should omit any event that's sending `Compiler`.

**Comment by stnwk** [comment]
Thanks!

**Comment by shellscape** [comment]
No worries. I have one more feature I want to get in before the next release. So please stand by for the fix to roll out.

**Comment by cpylua** [comment]
Same issue here, it's quite annoying. I have a script to restart webpack watch when some specific error occurs in webpack, now I have to CTRL+C to restart the whole process. Hope we can have the new release soon.

BTW, this plugin is awesome, thanks!

**Comment by shellscape** [comment]
@cpylua no worries. In the future please use one of the reaction buttons to show support for an issue.
