### ISSUE TITLE
Fail if `publicPath` is not specified

### ISSUE THREAD

**Issue by hudochenkov** [shellscape/webpack-plugin-serve#176]
- Webpack Version: 4.43.0
- Operating System (or Browser):
- Node Version:
- webpack-plugin-serve Version: 1.0.0

### How Do We Reproduce?

Remove `output.publicPath` in a webpack config, when using `webpack-plugin-serve@1.0.0`.

Problem was introduced in https://github.com/shellscape/webpack-plugin-serve/pull/156.

### Expected Behavior

No error.

### Actual Behavior

Following error is thrown:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at join (path.js:1147:7)
    at WebpackPluginServe.hook (/Users/aleks/project/node_modules/webpack-plugin-serve/lib/index.js:194:22)
    at WebpackPluginServe.apply (/Users/aleks/project/node_modules/webpack-plugin-serve/lib/index.js:132:10)
    at webpack (/Users/aleks/project/node_modules/webpack/lib/webpack.js:51:13)
    at run (/Users/aleks/project/node_modules/webpack-nano/lib/compiler.js:16:20)
    at doeet (/Users/aleks/project/node_modules/webpack-nano/bin/wp.js:78:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by shellscape** [comment]
Would you like to open a PR to fix this?
