### ISSUE TITLE
Circular structure serialization error

### ISSUE THREAD

**Issue by siilike** [shellscape/webpack-plugin-serve#192]
- Webpack Version: 5.4.0
- Operating System (or Browser):
- Node Version:
- webpack-plugin-serve Version: 1.2.0

### Actual Behavior

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Compiler'
    --- property 'root' closes the circle
    at JSON.stringify (<anonymous>)
    at prep (webpack-plugin-serve/1.2.0_webpack@5.4.0/node_modules/webpack-plugin-serve/lib/routes.js:14:29)
    at WebpackPluginServe.<anonymous> (webpack-plugin-serve/1.2.0_webpack@5.4.0/node_modules/webpack-plugin-serve/lib/routes.js:102:58)
    at WebpackPluginServe.emit (events.js:314:20)
    at WebpackPluginServe.emit (webpack-plugin-serve/1.2.0_webpack@5.4.0/node_modules/webpack-plugin-serve/lib/index.js:158:13)
    at webpack-plugin-serve/1.2.0_webpack@5.4.0/node_modules/webpack-plugin-serve/lib/index.js:210:35
    at Hook.eval [as callAsync] (eval at create (tapable/2.0.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (tapable/2.0.0/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (webpack/5.4.0_webpack-cli@4.1.0+webpack@5.4.0/node_modules/webpack/lib/Watching.js:183:28)
    at webpack/5.4.0_webpack-cli@4.1.0+webpack@5.4.0/node_modules/webpack/lib/Watching.js:108:21
```

**Comment by shellscape** [comment]
Reproductions are required for issues here. We also don't support Webpack 5 at the moment.

**Comment by siilike** [comment]
Anyone encountering the same issue can use my working fork here: https://github.com/siilike/webpack-plugin-serve
