### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by boojum** [shellscape/webpack-plugin-serve#199]
- Webpack Version: 5.6.0
- Operating System (or Browser): Linux with latest Firefox & Chrome
- Node Version: 15.2.1
- webpack-plugin-serve Version: 1.2.0

### How Do We Reproduce?

`webpack.config.js`
```
const path = require('path')
const { merge } = require('webpack-merge')
const parts = require('./webpack.parts')

const PATHS = {
  src: path.resolve('src'),
  dist: path.resolve('dist'),
  assets: path.join(path.resolve('dist'), 'assets'),
}

const commonConfig = merge([
  { entry: [path.join(PATHS.src, 'index.jsx')] },
  { resolve: { extensions: ['*', '.js', '.jsx'] } },
  parts.page({
    title: 'React + Webpack',
    template: path.join(PATHS.src, 'index.html'),
  }),
  parts.loadJS({ include: PATHS.src }),
  parts.loadCSS(),
])

const productionConfig = merge([])

const developmentConfig = merge([
  { entry: ['webpack-plugin-serve/client'] },
  parts.addDependency({ path: path.join(PATHS.src, 'index.html') }),
  parts.devServer({ assets: PATHS.assets }),
])

const getConfig = (mode) => {
  switch (mode) {
    case 'production':
      return merge(commonConfig, productionConfig, { mode })
    case 'development':
      return merge(commonConfig, developmentConfig, { mode })
    default:
      throw new Error(`Trying to use an unknown mode, ${mode}`)
  }
}

module.exports = (env, argv) => {
  return getConfig(argv.mode)
}
```
`webpack.parts.js`

```
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const { WebpackPluginServe } = require('webpack-plugin-serve')
const { AddDependencyPlugin } = require('webpack-add-dependency-plugin')

exports.addDependency = (path) => ({
  plugins: [new AddDependencyPlugin({ path })],
})

exports.devServer = ({ assets, port = 8080 }) => ({
  watch: true,
  plugins: [
    new WebpackPluginServe({
      port,
      static: assets,
      ramdisk: true,
      waitForBuild: true,
      historyFallback: true,
      log: { level: 'info', timestamp: true },
      progress: 'minimal',
    }),
  ],
})

exports.page = ({ title, template }) => ({
  plugins: [
    new HtmlWebpackPlugin({
      title,
      template,
    }),
  ],
})

exports.loadCSS = () => ({
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true,
            },
          },
        ],
      },
    ],
  },
})

exports.loadJS = ({ include }) => ({
  module: {
    rules: [
      {
        test: /\.js(x?)$/,
        include,
        use: ['babel-loader', 'eslint-loader'],
      },
    ],
  },
})

```
### Expected Behavior

`wp --mode development` should compile the configuration and run `webpack-plugin-serve` without any issues.

### Actual Behavior

```
> react-template@0.0.1 start
> wp --mode development

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:277:15)
    at validateString (node:internal/validators:123:11)
    at basename (node:path:1156:5)
    at WebpackPluginServe.init (/home/boojum/Projects/react/node_modules/webpack-plugin-serve/lib/plugins/ramdisk.js:59:25)
    at WebpackPluginServe.hook (/home/boojum/Projects/react/node_modules/webpack-plugin-serve/lib/index.js:181:25)
    at WebpackPluginServe.apply (/home/boojum/Projects/react/node_modules/webpack-plugin-serve/lib/index.js:132:10)
    at createCompiler (/home/boojum/Projects/react/node_modules/webpack/lib/webpack.js:71:12)
    at create (/home/boojum/Projects/react/node_modules/webpack/lib/webpack.js:115:15)
    at webpack (/home/boojum/Projects/react/node_modules/webpack/lib/webpack.js:139:31)
    at f (/home/boojum/Projects/react/node_modules/webpack/lib/index.js:35:15)
```
I found issue #178, not sure if its relevant.

**Comment by TrySound** [comment]
Looks like `output: { path: '...' }` is missing in configuraition

**Comment by boojum** [comment]
> Looks like `output: { path: '...' }` is missing in configuration

Exactly that, thanks!
