### ISSUE TITLE
fatal error occurs when trying to stringify circular JSON structure

### ISSUE THREAD

**Issue by effervescentia** [shellscape/webpack-plugin-serve#211]
- Webpack Version: `5.18.0`
- Operating System (or Browser): `MacOS 11.2.1`
- Node Version: `15.2.0`
- webpack-plugin-serve Version: `1.0.1` and `1.2.0`

### How Do We Reproduce?

My current configuration is highly intertwined with out application architecture, but I will work to extract a minimal repository to reproduce. In the meantime this is my configuration:

These are the plugins I'm using:
`webpack.DefinePlugin`
`webpack.IgnorePlugin`
`webpack.BannerPlugin`

`html-webpack-plugin@5.1.0`
`webpackbar@5.0.0-3`
`case-sensitive-paths-webpack-plugin@2.3.0`

These are the loaders I'm using:
`babel-loader@8.2.2`
`@svgr/webpack@5.5.0`
`style-loader@2.0.0`
`css-loader@5.0.2`
`postcss-loader@5.0.0`
`file-loader@6.2.0`

One of my coworkers noticed [this recent change](https://github.com/shellscape/webpack-plugin-serve/pull/209) that appears to target the stringification, but this change has not yet been released anywhere. If we attempt to upgrade our version of `webpack-plugin-serve` to `1.2.1` then instead of this error we sporadically encounter javascript heap errors.

### Expected Behavior

circular JSON stringification errors should be reported with the event name to aide debugging and _should not_ break the watching & serving process

### Actual Behavior

error is thrown and will either kill the process outright, or occasionally just send it into a zombie state where it stops responding to file changes, but continues to serve the content from before it crashed

```
⬢ webpack: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Compiler'
    --- property 'root' closes the circle
    at JSON.stringify (<anonymous>)
    at prep (/Users/benteichman/development/voiceflow/creator-app/node_modules/webpack-plugin-serve/lib/routes.js:14:29)
    at WebpackPluginServe.<anonymous> (/Users/benteichman/development/voiceflow/creator-app/node_modules/webpack-plugin-serve/lib/routes.js:102:58)
    at WebpackPluginServe.emit (node:events:341:22)
    at WebpackPluginServe.EventEmitter.emit (node:domain:467:12)
    at WebpackPluginServe.emit (/Users/benteichman/development/voiceflow/creator-app/node_modules/webpack-plugin-serve/lib/index.js:158:13)
    at /Users/benteichman/development/voiceflow/creator-app/node_modules/webpack-plugin-serve/lib/index.js:210:35
    at Hook.eval [as callAsync] (eval at create (/Users/benteichman/development/voiceflow/creator-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:50:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/benteichman/development/voiceflow/creator-app/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/Users/benteichman/development/voiceflow/creator-app/node_modules/webpack/lib/Watching.js:215:28)
(node:24873) [DEP_WEBPACK_COMPILATION_ADDITIONAL_CHUNK_ASSETS] DeprecationWarning: additionalChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:24873) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:24873) [DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:24873) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
```

**Comment by shellscape** [comment]
Yeah we'll definitely need a _minimal_ reproduction to solve this. It's likely highly specific to your implementation.
