### ISSUE TITLE
Random crash 

### ISSUE THREAD

**Issue by malj** [shellscape/webpack-plugin-serve#229]
- Webpack Version: 5.47.9
- Operating System (or Browser): Ubuntu 20.04.2 (WSL 2)
- Node Version: 16.6.0
- webpack-plugin-serve Version: 1.5.0

### How Do We Reproduce?

Run Webpack CLI in watch mode with the following config:

```js
new ServePlugin({
    progress: "minimal",
    host: "localhost",
    hmr: "refresh-on-failure",
})
```

### Expected Behavior

No crashes

### Actual Behavior

Webpack process randomly crashes after a while (cca 15 minutes on my machine with Intel i7-8750H and 32 GB RAM) with the following console output:

```
[webpack-cli] TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at stringify (/path/to/my/project/node_modules/json-stringify-safe/stringify.js:5:15)
    at prep (/path/to/my/project/node_modules/webpack-plugin-serve/lib/routes.js:15:24)
    at WebpackPluginServe.<anonymous> (/path/to/my/project/node_modules/webpack-plugin-serve/lib/routes.js:103:58)
    at WebpackPluginServe.emit (node:events:406:35)
    at WebpackPluginServe.emit (/path/to/my/project/node_modules/webpack-plugin-serve/lib/index.js:158:13)
    at /path/to/my/project/node_modules/webpack-plugin-serve/lib/index.js:210:35
    at Hook.eval [as callAsync] (eval at create (/path/to/my/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/path/to/my/project/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/path/to/my/project/node_modules/webpack/lib/Watching.js:273:28)
```

Related issues:

- https://github.com/moll/json-stringify-safe/issues/33
- https://github.com/GoogleChromeLabs/jsbi/issues/30

**Comment by shellscape** [comment]
This is an issue with json-stringify-safe, not this lib.

**Comment by malj** [comment]
I know, I submitted a [PR](https://github.com/moll/json-stringify-safe/pull/35), but the lib was last updated in 2015 so I'm not expecting it to be merged anytime soon.

I'm not even sure where big ints are coming from because I'm not using them in my code, but the [fix](https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-521460510) seems fairly trivial. I was hoping you'd consider patching it with a custom replacer, if it wouldn't affect anything else. It's a bit tedious having to kill orphaned child processes and restart webpack several times per hour while working with this plugin.

**Comment by shellscape** [comment]
Yeah the last thing I want to do is handle stringifying myself. Not a fun thing. You might be able to contact the maintainer via Twitter or email.
