### ISSUE TITLE
Refreshing the page causes ERR_STREAM_WRITE_AFTER_END error

### ISSUE THREAD

**Issue by G-Rath** [shellscape/webpack-plugin-serve#47]
When refreshing the page with `hmr` enabled (and connected via websocket to the serve server), an exception is logged to the webpack console.

This doesn't actually stop anything from working.

- Webpack Version: `v4.26.1`
- Operating System (or Browser): `Windows 10, Chrome 71.0.3578.80`
- Node Version: `v10.14.1`
- webpack-plugin-dev Version: `v0.1.2`

### How Do We Reproduce?

https://github.com/G-Rath/js-bugs/tree/base/webpack-plugin-serve

### Expected Behavior
No errors in webpack console when refreshing page.

### Actual Behavior

Error is logged:

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
      at writeAfterEnd (_stream_writable.js:243:12)
      at Socket.Writable.write (_stream_writable.js:291:5)
      at Sender.sendFrame (C:\Users\G-Rath\workspace\projects-personal\js-bugs\node_modules\ws\lib\sender.js:404:20)
      at Sender.doClose (C:\Users\G-Rath\workspace\projects-personal\js-bugs\node_modules\ws\lib\sender.js:141:10)
      at Sender.close (C:\Users\G-Rath\workspace\projects-personal\js-bugs\node_modules\ws\lib\sender.js:128:12)
      at WebSocket.close (C:\Users\G-Rath\workspace\projects-personal\js-bugs\node_modules\ws\lib\websocket.js:215:18)
      at Receiver.receiverOnConclude (C:\Users\G-Rath\workspace\projects-personal\js-bugs\node_modules\ws\lib\websocket.js:695:32)
      at Receiver.emit (events.js:182:13)
      at Receiver.controlMessage (C:\Users\G-Rath\workspace\projects-personal\js-bugs\node_modules\ws\lib\receiver.js:436:14)
      at Receiver.getData (C:\Users\G-Rath\workspace\projects-personal\js-bugs\node_modules\ws\lib\receiver.js:330:42)
```

**Comment by PlayMa256** [comment]
I tested locally, even forcing a refresh (ctrl + shift + R) and i did not get an error... i'll see if i can create a windows box to test those types of problems.

**Comment by shellscape** [comment]
Confirmed. The node maintainers have identified this as a regression that snuck in. The solution is to use 10.0.0 - 10.13.0 until that gets fixed. Given that this is confirmed an upstream problem that's affecting more than this module, I'm gonna close it.

Cheers for reporting this originally, you helped a great many people by pointing out the problem 🍻

**Comment by G-Rath** [comment]
@shellscape could you link to the relevant material on the node side of things, so we can watch the issue?

**Comment by shellscape** [comment]
Yeah for sure https://github.com/nodejs/node/issues/24958

**Comment by shellscape** [comment]
@lxe in theory it should be :) haven't tested it yet.
