### ISSUE TITLE
cheap-module-source-map bug

### ISSUE THREAD

**Issue by pronevich** [shellscape/webpack-plugin-serve#60]
- Webpack Version: 4.27.1
- Operating System (or Browser): macOS Mojave 
- Node Version: 10.13
- webpack-plugin-serve Version: 0.2.2

### How Do We Reproduce?

1. Use react example in recipes folder of this repo
2. Change webpack config `devtool` to `cheap-module-source-map` value
3. Run server and change some code for hot reload

### Expected Behavior
server should work

### Actual Behavior
server stops on error

```
/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/SourceMapDevToolPlugin.js:36
        if (asset.sourceAndMap) {
                  ^

TypeError: Cannot read property 'sourceAndMap' of undefined
    at getTaskForFile (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/SourceMapDevToolPlugin.js:36:12)
    at files.forEach (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/SourceMapDevToolPlugin.js:136:20)
    at Array.forEach (<anonymous>)
    at compilation.hooks.afterOptimizeChunkAssets.tap (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/SourceMapDevToolPlugin.js:130:12)
    at SyncHook.eval [as call] (eval at create (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:14:1)
    at SyncHook.lazyCompileHook (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/Compilation.js:1313:42)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:10:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/Compilation.js:1309:36)
error Command failed with exit code 1.
```

**Comment by shellscape** [comment]
Thanks for reporting this. I'm offline for the night here, but would welcome any help in triaging this.

**Comment by shellscape** [comment]
@pronevich I'm unable to reproduce on my end. We're going to need a reproduction repo to work from, similar to what @TrySound created for us in the other issues.

**Comment by pronevich** [comment]
@shellscape sorry, forgot mention that wps should be updated to latest version 0.2

**Comment by pronevich** [comment]
@shellscape anyway here repo ) https://github.com/pronevich/wps-issue-60

**Comment by shellscape** [comment]
OK I narrowed down what is going on here - yet another webpack internal thing we're going to have to work around. I believe this is going to require a rethink of how we're overriding the HMR filenames.

**Comment by shellscape** [comment]
Further information: In `hmr-plugin.js` we're overriding asset names to get around some bad behavior in webpack with regard to HMR. in most cases that seems to have done the trick. However, in the source map code. they're not using assets. Rather, they're using `chunks.[chunk].file`. While the assets in the compilation are correct, the chunk files are not. This poses a significant challenge to overcome.
