### ISSUE TITLE
Socket errors during recompile

### ISSUE THREAD

**Issue by thomb** [shellscape/webpack-plugin-serve#92]
- Webpack Version: "4.28.4
- Operating System (or Browser): MacOS v10.14.2
- Node Version: v11.6.0
- webpack-plugin-serve Version: 2.0.3

### How Do We Reproduce?

Currently these crashes seem to happen at random when saving files or switching between branches but `webpack-plugin-serve` crashes hard during recompiling.

### Expected Behavior
That `webpack-serve-plugin` would recompiled the code and force a browser refresh.

### Actual Behavior

`webpack-serve-plugin` crashes during recompilation with the following error stack

```
⬡ wps: Server Listening on: http://192.168.86.130:8083

✓ App bundle compiled
^[^[✓ App bundle compiled
node_modules/ws/lib/websocket.js:328
      throw err;
      ^

Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (node_modules/ws/lib/websocket.js:322:19)                                                                                              
    at WebpackPluginServe.socket.progress (node_modules/webpack-plugin-serve/lib/routes.js:85:16)                                                            
    at WebpackPluginServe.emit (events.js:188:13)
    at ProgressPlugin (ode_modules/webpack-plugin-serve/lib/index.js:197:16)                                                                                
    at Object.call (node_modules/webpack/lib/ProgressPlugin.js:304:6)                                                                                        
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:8:18)                            
    at AsyncSeriesHook.lazyCompileHook (node_modules/tapable/lib/Hook.js:154:20)                                                                             
    at asyncLib.forEach.err (node_modules/webpack/lib/Compiler.js:358:27)                                                                                    
    at node_modules/neo-async/async.js:2825:7
    at done (node_modules/neo-async/async.js:2861:11)
error Command failed with exit code 1.

```
This is the only part of the crash which seems to be consistent, i.e. this crash complains about a closing socket)

cc: @EvHaus

**Comment by shellscape** [comment]
The `Error: WebSocket is not open: readyState 2 (CLOSING)` error typically happens when a connected socket is closing and an attempt to send a message is initiated. That would mean that the client (the browser) would have to be in the state of closing the socket, and that should only happen on refresh or when the page is loading. It's super weird that you're getting that problem on recompile. Without more information/code/configuration I couldn't tell you why that might be happening, as it's probably dependent upon your specific setup, as most webpack-related issues tend to be.

**Comment by thomb** [comment]
I still don't have a rock solid repro case, but there are some correlations I can pass along.

If the browser is refreshed when the application is recompiling I will notice output like the following:
```
⬡ wps: Server Listening on: http://192.168.86.130:8083                                                                                                  
✓ App bundle compiled
                                                                                                
  Error: write EPIPE
      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:66:16)      
                                                                                                

  Error: write EPIPE                                                                            
      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:66:16)      
                                                                                                
                                                                                                
  Error: write EPIPE                                                                            
      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:66:16)      
                                                                                                

  Error: write EPIPE                                                                            
      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:66:16)      

                                                                                                
  Error: write EPIPE
      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:66:16)      

✓ App bundle compiled
node_modules/ws/lib/websocket.js:328                       
      throw err;
      ^

Error: WebSocket is not open: readyState 2 (CLOSING)                                            
```

Crashes do _not_ always follow the ` Error: write EPIPE` output, but they are frequently (though not always) correlated.

**Comment by shellscape** [comment]
`EPIPE` is a new one. Can you confirm whether the same errors occur on Node v10?

**Comment by shellscape** [comment]
We've made some improvements to the socket communication (which is the likely culprit here) and will be releasing that shortly. Given the issue's age, last comment date, and the number of improvements we've made since, we're going to close this one. If it pops back up again, please don't hesitate to drop a comment and we'll reopen.
